services:
  postgres:
    container_name: student-market-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
#      interval: 2s
#      timeout: 10s
#      retries: 5

  minio:
    container_name: student-market-minio
    image: minio/minio
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ACCESS_KEY: minioadmin     # Set your own access key
      MINIO_SECRET_KEY: minioadmin      # Set your own secret key
    command: server /data --console-address ":9001"

#  app:
#    container_name: student-market-server
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8085:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy
#    env_file:
#      - .env



volumes:
  postgres_data:

