SERVER_PORT: 8021

PORT_DB: 5421
POSTGRESQL_DATABASE: postgres
POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: 9
POSTGRES_HOST: localhost

spring:
  docker:
    compose:
      file: local/docker-compose.yaml
minio:
  url : http://localhost:9009