server:
  port: 8085
spring:
  jpa:
    properties:
      hibernate:
        format_sql=true:
        connection:
          password: 9
          username: postgres
          url: jdbc:postgresql://localhost:5433/postgres
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    user: postgres
    password: 9
    url: jdbc:postgresql://localhost:5433/postgres
    locations: classpath:db/migrations
    schemas: public
    table: flyway_schema_history
    baseline-on-migrate: true
#logging:
#  level:
#    org.flywaydb: DEBUG
