server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${PORT_DB}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true
    show-sql: true
  flyway:
    user: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${PORT_DB}/${POSTGRESQL_USERNAME}  # Updated to use the service name
    locations: classpath:db/migrations
    schemas: public
    table: flyway_schema_history
    baseline-on-migrate: true

#  web:
#    locale: en
#    locale-resolver: fixed
minio:
  url : http://${MINIO_HOST}:${MINIO_PORT}